version: "3.3"
services:
  web:
    image: moonshot_web:latest
    depends_on:
    - mongo
    ports:
     # Image that I created runs on port 3000.
    - 3000
    environment:
      # Port used by the HAProxy to reach the service.
      - SERVICE_PORTS=3000
  mongo:
    image: mongo
    volumes:
    - /data/db
    ports:
    - "27017:27017"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always
  lb:
    image: dockercloud/haproxy
    ports:
      - 8001:80
    links:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

