version: "2.3"
services:
  web:
    build: .
    depends_on:
    - mongo
    scale: 3
  mongo:
    container_name: mongo
    image: mongo
    volumes:
    - /data/db
    ports:
    - "27017:27017"
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always
  nginx:
    image: nginx:stable-alpine
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./var/log/nginx:/var/log/nginx
      # It needs to access Docker's API, so we mount the Unix socket
    ports:
    - "8000:80"
